[package]
name = "nihilsweeper"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
iced = { version = "0.14.0", features = ["canvas", "image"] }
log = { version = "0.4.29", features = ["std", "serde", "release_max_level_info"] }
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
resvg = "0.45"
usvg = "0.45"
tiny-skia = "0.11"
image = "0.25.9"
