unstable_features = true
max_width = 120
comment_width = 100
doc_comment_code_block_width = 120
format_code_in_doc_comments = true
imports_granularity = "Crate"
wrap_comments = true
format_strings = true
error_on_line_overflow = true
error_on_unformatted = false
show_parse_errors = true
condense_wildcard_suffixes = true
format_macro_matchers = true
match_block_trailing_comma = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
